server:
  port: 8080
spring:
  application:
    name: @project.artifactId@
  output:
    ansi:
      enabled: always
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: localhost:29092
    topic: "my-topic-name"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
          spring.json.trusted.packages: com.reuven.kafka.demo.entities
          spring.json.value.default.type: com.reuven.kafka.demo.entities.MyEvent
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "${spring.kafka.producer.properties.spring.json.trusted.packages}"
        spring.json.value.default.type: "${spring.kafka.producer.properties.spring.json.value.default.type}"
      auto-offset-reset: earliest
      group-id: myId